ransom_gr_publicite_Admin_publicite:
    resource: "@RansomGrPubliciteBundle/Resources/config/routing/publicite.yml"
    prefix:   /Admin/publicite

ransom_gr_publicite_homepage:
    path:     /Admin/NewPub
    defaults: { _controller: RansomGrPubliciteBundle:Publicite:AddnewPublicite }
