security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
       main:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               success_handler: authentication.handler.login_success_handler
               #csrf_provider: form.csrf_provider
           logout:
               target : /login
           anonymous:    true
#allow_if: "not has_role('ROLE_USER') and not has_role('ROLE_ADMIN')"
#allow_if: "not has_role('ROLE_USER') and not has_role('ROLE_ADMIN')"
    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login2$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/welcome, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/Admin, role: ROLE_ADMIN }
    - { path: ^/Admin/, role: ROLE_ADMIN }
    - { path: ^/Admin/^, role: ROLE_ADMIN }
    - { path: ^/Client/^, role: ROLE_USER }



