FO_matching_homepage:
    path:     /Client/FO_matching_homepage
    defaults: { _controller: NadiaMatchingBundle:Default:FO_MatchingHomepage }

FO_voirpackagings:
    path:     /Client/FO_voirpackaging
    defaults: { _controller: NadiaMatchingBundle:Default:FO_Packagings }

FO_ajouterpref:
    path:     /Client/FO_ajouterpref
    defaults: { _controller: NadiaMatchingBundle:Default:FO_AjoutPref }


FO_inviter:
    path:     /Client/FO_inviter{id}
    defaults: { _controller: NadiaMatchingBundle:Invitation:FO_Inviter }


BO_ajouterpack:
    path:     /Admin/BO_ajouterpack
    defaults: { _controller: NadiaMatchingBundle:Packaging:Ajout }

BO_afficherpack:
    path:     /Admin/BO_afficherpack
    defaults: { _controller: NadiaMatchingBundle:Packaging:affichage }

BO_modifpack:
    path:     /Admin/BO_modifpack{id}
    defaults: { _controller: NadiaMatchingBundle:Packaging:update }

BO_supppack:
    path:     /Admin/BO_supppack{id}
    defaults: { _controller: NadiaMatchingBundle:Packaging:delete }


