_homepage:
    path:     /welcome
    defaults: { _controller: MySoulMateMainBundle:Main:index }
_Dashpage:
    path:     /Admin
    defaults: { _controller: MySoulMateMainBundle:Main:Admin }
_Login_page:
    path:     /welcome/login
    defaults: { _controller: MySoulMateMainBundle:Main:loginClient }