_homepage:
    path:     /welcome
    defaults: { _controller: MySoulMateMainBundle:Main:index }
_Dashpage:
    path:     /Admin
    defaults: { _controller: MySoulMateMainBundle:Main:Admin }
_Login_page:
    path:     /welcome/login
    defaults: { _controller: MySoulMateMainBundle:Main:loginClient }
_CodeNameOne_login:
    path:     /User
    defaults: { _controller: MySoulMateMainBundle:Main:LoginClient2 }

_CodeNameOne_new:
    path:     /User/addnew
    defaults: { _controller: MySoulMateMainBundle:Main:addnew }
_CodeNameOne_recover:
    path:    /User/recover
    defaults: { _controller: MySoulMateMainBundle:Main:Recover}
