<?php

namespace RansomGr\PubliciteBundle\Repository;

/**
 * PubliciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllordered()
    {
        $query= $this->getEntityManager()->createQuery('SELECT p,pp FROM RansomGrPubliciteBundle:Publicite p JOIN  p.position pp ORDER BY  pp.position ASC');
        return $query->getResult();
    }



}
