<?php

namespace RansomGr\PubliciteBundle\Repository;

/**
 * PubOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
