<?php

namespace RansomGr\PubliciteBundle\Repository;

/**
 * PubPosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubPosRepository extends \Doctrine\ORM\EntityRepository
{
}
