amira_events_homepage:
    path:     /
    defaults: { _controller: AmiraEventsBundle:Default:index }

_ajouter:
    path:     /Admin/Events/ajouter
    defaults: { _controller: AmiraEventsBundle:BoEventsController:Ajouter }

_modifier:
    path:     /Admin/Events/modifier/{id}
    defaults: { _controller: AmiraEventsBundle:BoEventsController:Modifier }

_listing:
    path:     /Admin/Events/listing
    defaults: { _controller: AmiraEventsBundle:BoEventsController:Listing }

_delete:
    path:     /Admin/Events/delete/{id}
    defaults: { _controller: AmiraEventsBundle:BoEventsController:Delete }

FO_ajouter:
    path:     /foajouter
    defaults: { _controller: AmiraEventsBundle:FoEventsController:Ajouter }

FO _modifier:
    path:     /fomodifier/{id}
    defaults: { _controller: AmiraEventsBundle:FoEventsController:Modifier }

FO_listing:
    path:     /folisting
    defaults: { _controller: AmiraEventsBundle:FoEventsController:Listing }

FO_delete:
    path:     /fodelete/{id}
    defaults: { _controller: AmiraEventsBundle:FoEventsController:Delete }

FO_QR:
    path:     /QR/{id}
    defaults: { _controller: AmiraEventsBundle:FoEventsController:QR }
